"""initial2

Revision ID: 51f516f1c449
Revises: 6202494bf137
Create Date: 2017-12-05 11:56:27.828485

"""

# revision identifiers, used by Alembic.
revision = '51f516f1c449'
down_revision = '6202494bf137'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('list', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('list', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('listitem', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('listitem', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('listitem', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listitem', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('listitem', 'updated_at')
    op.drop_column('listitem', 'created_at')
    op.drop_column('list', 'updated_at')
    op.drop_column('list', 'created_at')
    # ### end Alembic commands ###
